In [11]:
# import pandas as pd
# df1 = pd.read_csv('处理后无干扰的数据.csv')
# df2 = pd.read_csv('处理后有干扰的数据.csv')
import os

In [67]:
dic = {}
for name,i in df2.groupby('code'):
    dic[name] =int( len(i)/0.5)
dic

{1: 176,
 2: 136,
 3: 142,
 4: 168,
 5: 196,
 6: 208,
 7: 222,
 8: 236,
 9: 188,
 10: 176,
 11: 192,
 12: 202,
 13: 140,
 14: 130,
 15: 118,
 16: 182,
 17: 274,
 18: 232,
 19: 168,
 20: 148,
 21: 156,
 22: 118,
 23: 122,
 24: 112,
 25: 128,
 26: 138,
 27: 182,
 28: 164,
 29: 96,
 30: 140,
 31: 152,
 32: 168,
 33: 180,
 34: 130,
 35: 164,
 36: 272,
 37: 134,
 38: 144,
 39: 122,
 40: 180,
 41: 102,
 42: 134,
 43: 160,
 44: 182,
 45: 126,
 46: 144,
 47: 160,
 48: 154,
 49: 158,
 50: 180,
 51: 116,
 52: 102,
 53: 114,
 54: 138,
 55: 138,
 56: 126,
 57: 138,
 58: 154,
 59: 118,
 60: 126,
 61: 124,
 62: 116,
 63: 128,
 64: 142,
 65: 134,
 66: 158,
 67: 100,
 68: 142,
 69: 180,
 70: 106,
 71: 146,
 72: 110,
 73: 150,
 74: 198,
 75: 102,
 76: 92,
 77: 120,
 78: 116,
 79: 102,
 80: 116,
 81: 108,
 82: 126,
 83: 174,
 84: 164,
 85: 184,
 86: 194,
 87: 210,
 88: 176,
 89: 166,
 90: 216,
 91: 254,
 92: 160,
 93: 266,
 94: 202,
 95: 178,
 96: 222,
 97: 192,
 98: 280,
 99: 238,
 100: 196,
 101: 200,
 102: 198,
 103: 196,
 104: 264,
 105: 220,
 106: 228,
 107: 196,
 108: 190,
 109: 190,
 110: 180,
 111: 240,
 112: 196,
 113: 282,
 114: 216,
 115: 306,
 116: 264,
 117: 224,
 118: 140,
 119: 200,
 120: 144,
 121: 214,
 122: 172,
 123: 190,
 124: 218,
 125: 172,
 126: 162,
 127: 160,
 128: 188,
 129: 218,
 130: 230,
 131: 180,
 132: 198,
 133: 202,
 134: 210,
 135: 178,
 136: 210,
 137: 164,
 138: 120,
 139: 168,
 140: 216,
 141: 176,
 142: 224,
 143: 170,
 144: 142,
 145: 112,
 146: 108,
 147: 184,
 148: 162,
 149: 258,
 150: 168,
 151: 202,
 152: 146,
 153: 170,
 154: 244,
 155: 168,
 156: 148,
 157: 200,
 158: 198,
 159: 190,
 160: 214,
 161: 176,
 162: 176,
 163: 178,
 164: 136,
 165: 188,
 166: 140,
 167: 134,
 168: 148,
 169: 172,
 170: 178,
 171: 136,
 172: 138,
 173: 156,
 174: 160,
 175: 170,
 176: 170,
 177: 152,
 178: 152,
 179: 176,
 180: 188,
 181: 160,
 182: 142,
 183: 164,
 184: 172,
 185: 170,
 186: 136,
 187: 134,
 188: 126,
 189: 158,
 190: 160,
 191: 136,
 192: 132,
 193: 146,
 194: 206,
 195: 142,
 196: 152,
 197: 146,
 198: 176,
 199: 106,
 200: 156,
 201: 142,
 202: 122,
 203: 154,
 204: 132,
 205: 150,
 206: 194,
 207: 126,
 208: 130,
 209: 152,
 210: 170,
 211: 162,
 212: 168,
 213: 164,
 214: 172,
 215: 162,
 216: 170,
 217: 138,
 218: 156,
 219: 184,
 220: 154,
 221: 146,
 222: 136,
 223: 150,
 224: 156,
 225: 128,
 226: 156,
 227: 296,
 228: 170,
 229: 144,
 230: 180,
 231: 146,
 232: 184,
 233: 164,
 234: 126,
 235: 148,
 236: 96,
 237: 152,
 238: 148,
 239: 136,
 240: 196,
 241: 124,
 242: 134,
 243: 146,
 244: 182,
 245: 172,
 246: 128,
 247: 136,
 248: 178,
 249: 154,
 250: 116,
 251: 148,
 252: 128,
 253: 128,
 254: 144,
 255: 156,
 256: 134,
 257: 156,
 258: 120,
 259: 138,
 260: 138,
 261: 102,
 262: 158,
 263: 172,
 264: 132,
 265: 158,
 266: 144,
 267: 142,
 268: 128,
 269: 168,
 270: 184,
 271: 146,
 272: 130,
 273: 150,
 274: 152,
 275: 132,
 276: 138,
 277: 172,
 278: 176,
 279: 144,
 280: 218,
 281: 166,
 282: 172,
 283: 184,
 284: 186,
 285: 166,
 286: 246,
 287: 166,
 288: 200,
 289: 182,
 290: 160,
 291: 148,
 292: 182,
 293: 176,
 294: 184,
 295: 196,
 296: 210,
 297: 164,
 298: 144,
 299: 214,
 300: 204,
 301: 168,
 302: 198,
 303: 148,
 304: 160,
 305: 182,
 306: 186,
 307: 224,
 308: 182,
 309: 174,
 310: 180,
 311: 176,
 312: 182,
 313: 192,
 314: 146,
 315: 188,
 316: 208,
 317: 192,
 318: 204,
 319: 196,
 320: 144,
 321: 174,
 322: 172,
 323: 184,
 324: 216}

In [13]:
def transform(data):
    whole_tag = []
    name = data.columns[1]
    for i in data.groupby(name)['Tag0']:
        a = list(i[1])
        if len(a)<4:
            while True:
                a.append('nan')
                if len(a) == 4:
                    break
        time = i[0]
        a.append(time)
        whole_tag.append(a)
    data_fag = pd.DataFrame(whole_tag)
#     print(data_fag.head())
    if len(data_fag.columns) !=5:
        data_fag.drop(list(data_fag.columns[5:]), axis=1 , inplace = True)
    data_fag.columns = ['postion1' ,'postion2','postion3','postion4','time_tag' ]
    data_fag = data_fag.astype('float')
#     data_fag.columns = []
    return data_fag

In [68]:
path_anomaly = 'C:\\Users\\luzheng\\Desktop\\E\\异常数据\\'
path_true = 'C:\\Users\\luzheng\\Desktop\\E\\正常数据\\'
list_real = os.listdir('C:\\Users\\luzheng\\Desktop\\E\\异常数据\\')
dic1  = {}
for i in list_real:
    df = pd.read_csv(path_anomaly+i , sep = ':')
    name = i.split('.')[0]
    df = transform(df)
    dic1[name] = len(df)

In [69]:
import numpy as np
np.array(a.index).astype(int)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
       183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
       196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208,
       209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,
       222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234,
       235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
       248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260,
       261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273,
       274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286,
       287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299,
       300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312,
       313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324])

In [70]:
a = pd.DataFrame(dic1.values(),index = dic1.keys())
a.index = np.array(a.index).astype(int)
b = pd.DataFrame(dic.values(),index = dic.keys())
a.sort_index(inplace = True)
b.sort_index(inplace = True)

In [74]:
a.to_csv('干扰数据处理后组数.csv')

In [71]:
a['after_transfer'] = b.values

In [72]:
a.sum()

0                 95667
after_transfer    53958
dtype: int64

In [73]:
a.

       0  after_transfer
1    414             176
2    182             136
3    215             142
4    222             168
5    255             196
..   ...             ...
320  250             144
321  277             174
322  283             172
323  288             184
324  314             216

[324 rows x 2 columns]